//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientTable
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> HospitalNumber { get; set; }
        public string DateOnWard { get; set; }
        public string DischargeLocation { get; set; }
        public string DOB { get; set; }
    }
}
